# Generated by Django 5.1.2 on 2024-10-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom_user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='custom_user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='username',
        ),
    ]
