# Generated by Django 5.1.2 on 2024-10-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_custom_user_options_alter_custom_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
