# Generated by Django 5.1.2 on 2024-10-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_custom_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
