# Generated by Django 5.1.2 on 2024-10-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero_id', models.IntegerField(default=0)),
                ('icon', models.FileField(upload_to='images/', verbose_name='icon')),
                ('pro_pick', models.IntegerField(default=0)),
                ('pro_win', models.IntegerField(default=0)),
                ('pro_lose', models.IntegerField(default=0)),
            ],
        ),
    ]
