# Generated by Django 5.1.2 on 2024-12-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero_id', models.IntegerField(default=0)),
                ('icon', models.FileField(upload_to='images/', verbose_name='icon')),
                ('pro_pick', models.IntegerField(default=0)),
                ('pro_win', models.IntegerField(default=0)),
                ('pro_lose', models.IntegerField(default=0)),
                ('base_health', models.IntegerField(default=0)),
                ('base_health_regen', models.IntegerField(default=0)),
                ('base_mana', models.IntegerField(default=0)),
                ('base_mana_regen', models.IntegerField(default=0)),
                ('base_armor', models.IntegerField(default=0)),
                ('base_mr', models.IntegerField(default=0)),
                ('base_attack_min', models.IntegerField(default=0)),
                ('base_attack_max', models.IntegerField(default=0)),
                ('base_str', models.IntegerField(default=0)),
                ('base_agi', models.IntegerField(default=0)),
                ('base_int', models.IntegerField(default=0)),
                ('str_gain', models.IntegerField(default=0)),
                ('agi_gain', models.IntegerField(default=0)),
                ('int_gain', models.IntegerField(default=0)),
                ('attack_range', models.IntegerField(default=0)),
                ('projectile_speed', models.IntegerField(default=0)),
                ('attack_rate', models.IntegerField(default=0)),
                ('base_attack_time', models.IntegerField(default=0)),
                ('attack_point', models.IntegerField(default=0)),
                ('move_speed', models.IntegerField(default=0)),
                ('day_vision', models.IntegerField(default=0)),
                ('night_vision', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='images/', verbose_name='logo')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team_id', models.IntegerField(default=0, unique=True)),
                ('rating', models.FloatField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.teams')),
            ],
        ),
    ]
