# Generated by Django 5.1.2 on 2024-12-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team_id', models.IntegerField(default=0, unique=True)),
                ('rating', models.FloatField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='heroes',
            name='agi_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='attack_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='attack_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='attack_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_agi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_armor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_attack_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_attack_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_attack_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_health_regen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_mana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_mana_regen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_mr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='base_str',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='day_vision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='int_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='move_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='night_vision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='projectile_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroes',
            name='str_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.teams')),
            ],
        ),
    ]
