# Generated by Django 5.1.2 on 2024-12-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroes',
            options={'verbose_name_plural': 'Heroes'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='heroes',
            name='hero_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
