# Generated by Django 5.1.2 on 2024-12-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_heroes_agi_gain_alter_heroes_attack_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='attack_range',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_agi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_armor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_attack_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_attack_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_attack_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_health',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_health_regen',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_int',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_mana',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_mana_regen',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_mr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='base_str',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='day_vision',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='move_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='night_vision',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='projectile_speed',
            field=models.FloatField(default=0),
        ),
    ]
