# Generated by Django 5.1.4 on 2025-01-11 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_heroes_agi_gain_alter_heroes_attack_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroes',
            name='base_armor',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='base_attack_max',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='base_attack_min',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='base_attack_time',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='base_health',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='base_health_regen',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='base_mana',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='base_mana_regen',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='base_mr',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='day_vision',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='night_vision',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='projectile_speed',
        ),
    ]
